# Generated by Django 6.0.7 on 2026-08-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0002_alter_servico_ativo_alter_servico_duracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cargo', models.CharField(choices=[('CABELEIREIRA', 'Cabeleireira'), ('MANICURE', 'Manicure e pedicure'), ('MAQUIADORA', 'Maquiadora'), ('DESIGNER_SOBRANCELHAS', 'Designer de sobrancelhas'), ('ESTETICISTA', 'Esteticista'), ('RECEPCIONISTA', 'Recepcionista'), ('OUTRO', 'Outro')], max_length=40, verbose_name='Cargo')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Funcionário ativo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('servicos', models.ManyToManyField(blank=True, related_name='funcionarios', to='servicos.servico', verbose_name='Serviços realizados')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
