# Generated by Django 6.0.7 on 2026-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da semana')),
                ('aberto', models.BooleanField(default=True, verbose_name='Salão aberto')),
                ('hora_abertura', models.TimeField(blank=True, null=True, verbose_name='Hora de abertura')),
                ('hora_fechamento', models.TimeField(blank=True, null=True, verbose_name='Hora de fechamento')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['dia_semana'],
            },
        ),
    ]
