# Generated by Django 6.0.7 on 2026-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data bloqueada')),
                ('motivo', models.CharField(blank=True, help_text='Exemplo: viagem, férias, feriado ou curso.', max_length=200, verbose_name='Motivo')),
                ('dia_inteiro', models.BooleanField(default=True, verbose_name='Bloquear o dia inteiro')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Bloquear a partir de')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Bloquear até')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Data bloqueada',
                'verbose_name_plural': 'Datas bloqueadas',
                'ordering': ['data'],
            },
        ),
    ]
