"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# ==========================================================
# CAMINHOS DO PROJETO
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================================
# SEGURANÇA
# ==========================================================

SECRET_KEY = 'django-insecure-*f2xb-ufh9v1spp62^cg*yrb)-8799c59@)qi_s970pj!(+pxc'

DEBUG = True

ALLOWED_HOSTS = []


# ==========================================================
# APLICAÇÕES
# ==========================================================

INSTALLED_APPS = [

    # Apps do projeto

    "paginas",
    "contas",
    "servicos",
    "agendamentos",
    "painel",
    "funcionarios",
    "financeiro",
    "produtos",
    "avaliacoes",

    # Apps padrão do Django

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ==========================================================
# URLS PRINCIPAIS
# ==========================================================

ROOT_URLCONF = "core.urls"


# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [

    {

        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]


# ==========================================================
# WSGI
# ==========================================================

WSGI_APPLICATION = "core.wsgi.application"


# ==========================================================
# BANCO DE DADOS
# ==========================================================

DATABASES = {

    "default": {

        "ENGINE":
            "django.db.backends.sqlite3",

        "NAME":
            BASE_DIR / "db.sqlite3",

    }

}


# ==========================================================
# VALIDAÇÃO DE SENHAS
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",

    },

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",

    },

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",

    },

    {

        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",

    },

]


# ==========================================================
# IDIOMA E FUSO HORÁRIO
# ==========================================================

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# ==========================================================
# ARQUIVOS ESTÁTICOS
# CSS / JS / IMAGENS DO SITE
# ==========================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [

    BASE_DIR / "static",

]


# ==========================================================
# ARQUIVOS DE MÍDIA
# IMAGENS ENVIADAS PELO USUÁRIO / PRODUTOS
# ==========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ==========================================================
# AUTENTICAÇÃO
# ==========================================================

LOGIN_URL = "/contas/login/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/"


# ==========================================================
# USUÁRIO PERSONALIZADO
# ==========================================================

AUTH_USER_MODEL = "contas.Usuario"