# Generated by Django 6.0.7 on 2026-08-02 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0002_alter_servico_ativo_alter_servico_duracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data', '-horario'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_status',
            field=models.TextField(blank=True, help_text='Exemplo: cliente ligou informando que não poderá comparecer.', verbose_name='Motivo ou observação do status'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO_CLIENTE', 'Cancelado pela cliente'), ('CANCELADO_ADMIN', 'Cancelado pelo salão'), ('DESISTENCIA', 'Desistência informada'), ('NAO_COMPARECEU', 'Não compareceu'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=30, verbose_name='Status'),
        ),
    ]
