# Generated by Django 6.0.7 on 2026-08-19 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_options_agendamento_atualizado_em_and_more'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='funcionarios.funcionario', verbose_name='Profissional'),
        ),
    ]
