# Generated by Django 6.0.7 on 2026-08-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0003_agendamento_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartão de débito'), ('CREDITO', 'Cartão de crédito'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Forma de pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receita', to='agendamentos.agendamento', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
