# Generated by Django 6.0.4 on 2026-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.PositiveIntegerField(verbose_name='Duração (minutos)'),
        ),
    ]
